#!/usr/bin/env node
// generate-seed.mjs — select the 365 daily puzzles from sudoku_150000.json and
// emit an idempotent SQL seed for the sudoku_next Supabase database.
//
//   Composition: 37 very_easy + 146 easy + 145 medium + 37 hard = 365.
//   Selection:   very_easy/easy/medium by fun_score DESC then puzzle ASC;
//                hard by er_rating ASC (gentlest first) then puzzle ASC.
//   Order:       deterministically interleaved so difficulty varies day-to-day.
//   Output:      sudoku_next/supabase/seed.sql  (INSERT ... ON CONFLICT (puzzle)
//                DO UPDATE, setting position; publish_date/is_active untouched).
//
// Run from the sudoku-pipeline repo:  node scripts/generate-seed.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(__dirname, "../sudoku_150000.json");
const DEST = resolve(__dirname, "../../sudoku_next/supabase/seed.sql");

// Fixed tier order (also the interleave tie-break order).
export const TIER_QUOTA = [
  { name: "very_easy", n: 37 },
  { name: "easy", n: 146 },
  { name: "medium", n: 145 },
  { name: "hard", n: 37 },
];

const cmpPuzzle = (a, b) => (a.puzzle < b.puzzle ? -1 : a.puzzle > b.puzzle ? 1 : 0);

export function pickTier(all, difficulty, n) {
  const list = all.filter((p) => p.difficulty === difficulty);
  const key =
    difficulty === "hard"
      ? (a, b) => (a.er_rating - b.er_rating) || cmpPuzzle(a, b) // gentlest hard first
      : (a, b) => (b.fun_score - a.fun_score) || cmpPuzzle(a, b); // most fun first
  list.sort(key);
  if (list.length < n) throw new Error(`Tier '${difficulty}' has ${list.length} < ${n} needed`);
  return list.slice(0, n);
}

// Evenly weave tiers: at each slot emit the tier whose ideal cumulative share
// (len/total * slot) most exceeds what it has already taken. Fixed tier order
// breaks ties, so the result is deterministic.
export function interleave(tiers) {
  const total = tiers.reduce((s, t) => s + t.items.length, 0);
  const state = tiers.map((t) => ({ items: t.items, len: t.items.length, taken: 0, idx: 0 }));
  const out = [];
  for (let slot = 1; slot <= total; slot++) {
    let best = null;
    let bestScore = -Infinity;
    for (const s of state) {
      if (s.idx >= s.len) continue;
      const score = (s.len / total) * slot - s.taken;
      if (score > bestScore + 1e-9) {
        bestScore = score;
        best = s;
      }
    }
    best.taken++;
    out.push(best.items[best.idx++]);
  }
  return out;
}

export function selectDaily(all) {
  const tiers = TIER_QUOTA.map((q) => ({ name: q.name, items: pickTier(all, q.name, q.n) }));
  return interleave(tiers);
}

function pgTextArray(arr) {
  if (!arr || arr.length === 0) return `'{}'`;
  return `array[${arr.map((t) => `'${String(t).replace(/'/g, "''")}'`).join(",")}]`;
}

function valuesRow(p, position) {
  const givens = Number.isFinite(p.givens) ? p.givens : "null";
  const funScore = Number.isFinite(p.fun_score) ? p.fun_score : "null";
  const erRating = p.er_rating == null ? "null" : Number(p.er_rating);
  return `  ('${p.puzzle}', '${p.solution}', '${p.difficulty}', ${pgTextArray(p.techniques)}, ${givens}, ${funScore}, ${erRating}, ${position})`;
}

export function toSeedSql(daily) {
  const rows = daily.map((p, i) => valuesRow(p, i + 1)).join(",\n");
  const counts = TIER_QUOTA.map((q) => `${q.n} ${q.name}`).join(" + ");
  return `-- seed.sql — the 365 daily Sudoku puzzles (${counts}).
-- GENERATED by sudoku-pipeline/scripts/generate-seed.mjs — do not edit by hand.
-- Idempotent: safe to re-run. publish_date and is_active are intentionally NOT
-- overwritten on conflict, so owner-assigned release dates survive a re-seed.
-- Positions 1..365 are deterministically interleaved so difficulty varies daily.

insert into public.puzzles
  (puzzle, solution, difficulty, techniques, givens, fun_score, er_rating, position)
values
${rows}
on conflict (puzzle) do update set
  solution   = excluded.solution,
  difficulty = excluded.difficulty,
  techniques = excluded.techniques,
  givens     = excluded.givens,
  fun_score  = excluded.fun_score,
  er_rating  = excluded.er_rating,
  position   = excluded.position;
`;
}

function main() {
  const all = JSON.parse(readFileSync(SRC, "utf8"));
  const daily = selectDaily(all);
  writeFileSync(DEST, toSeedSql(daily));
  const counts = TIER_QUOTA.map((q) => `${daily.filter((p) => p.difficulty === q.name).length} ${q.name}`).join(" + ");
  console.log(`Wrote ${daily.length} daily puzzles (${counts}) to ${DEST}`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
