#!/usr/bin/env node
// generate-library.mjs — emit the FULL 10,000-puzzle library as an idempotent
// SQL load for the sudoku_next Supabase database.
//
//   Source:  sudoku-pipeline/sudoku_10000.json (all 10k puzzles)
//   Output:  sudoku_next/supabase/puzzles_library.sql
//            INSERT ... ON CONFLICT (puzzle) DO NOTHING, batched.
//
//   Idempotent: safe to re-run. DO NOTHING means the curated 100 already in the
//   DB (which carry owner-assigned position/publish_date) are left untouched;
//   only puzzles whose `puzzle` string isn't present yet get inserted. The
//   library rows load with position/publish_date null — they are the content
//   pool, distinct from the curated 100 in seed.sql.
//
// Run from the sudoku-pipeline repo:  node scripts/generate-library.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(__dirname, '../sudoku_10000.json');
const DEST = resolve(__dirname, '../../sudoku_next/supabase/puzzles_library.sql');

const BATCH_SIZE = 500; // rows per INSERT statement
const ALLOWED = new Set(['very_easy', 'easy', 'medium', 'hard']); // matches the difficulty CHECK

// Postgres text[] literal, e.g. array['naked_singles','hidden_pairs'].
function pgTextArray(arr) {
  if (!arr || arr.length === 0) return `'{}'`;
  return `array[${arr.map((t) => `'${String(t).replace(/'/g, "''")}'`).join(',')}]`;
}

function valuesRow(p) {
  const puzzle = `'${p.puzzle}'`;
  const solution = `'${p.solution}'`;
  const difficulty = `'${p.difficulty}'`;
  const techniques = pgTextArray(p.techniques);
  const givens = Number.isFinite(p.givens) ? p.givens : 'null';
  const funScore = Number.isFinite(p.fun_score) ? p.fun_score : 'null';
  const erRating = p.er_rating == null ? 'null' : Number(p.er_rating);
  return `  (${puzzle}, ${solution}, ${difficulty}, ${techniques}, ${givens}, ${funScore}, ${erRating})`;
}

const all = JSON.parse(readFileSync(SRC, 'utf8'));

// Validate before emitting — fail loudly rather than push bad rows to prod.
const seen = new Set();
for (const p of all) {
  if (typeof p.puzzle !== 'string' || p.puzzle.length !== 81)
    throw new Error(`Bad puzzle length: ${p.puzzle}`);
  if (typeof p.solution !== 'string' || p.solution.length !== 81)
    throw new Error(`Bad solution length for puzzle ${p.puzzle}`);
  if (!ALLOWED.has(p.difficulty))
    throw new Error(`Disallowed difficulty '${p.difficulty}' (CHECK would reject)`);
  if (seen.has(p.puzzle)) throw new Error(`Duplicate puzzle in source: ${p.puzzle}`);
  seen.add(p.puzzle);
}

const header = `-- puzzles_library.sql — the FULL ${all.length}-puzzle content library.
-- GENERATED by sudoku-pipeline/scripts/generate-library.mjs — do not edit by hand.
-- Idempotent: INSERT ... ON CONFLICT (puzzle) DO NOTHING. Re-running inserts only
-- puzzles not already present; the curated 100 in seed.sql keep their
-- position/publish_date. Library rows load with position/publish_date null.
`;

const cols = '  (puzzle, solution, difficulty, techniques, givens, fun_score, er_rating)';
const statements = [];
for (let i = 0; i < all.length; i += BATCH_SIZE) {
  const rows = all.slice(i, i + BATCH_SIZE).map(valuesRow).join(',\n');
  statements.push(
    `insert into public.puzzles\n${cols}\nvalues\n${rows}\non conflict (puzzle) do nothing;`,
  );
}

writeFileSync(DEST, `${header}\n${statements.join('\n\n')}\n`, 'utf8');
console.log(`Wrote ${all.length} puzzles in ${statements.length} batches to ${DEST}`);
