name: Security Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: semgrep/semgrep-action@v1
        with:
          config: auto

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/path \
          ghcr.io/gitleaks/gitleaks:latest detect \
          --source="/path" \
          --verbose
